import jsPDF from 'jspdf';

export const generatePDFReport = (analysis, filename) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxLineWidth = pageWidth - (margin * 2);
  let yPos = 20; // Vertical cursor position

  // Helper to add text and move cursor down
  const addText = (text, fontSize = 12, fontType = 'normal', color = [0, 0, 0]) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", fontType);
    doc.setTextColor(...color);
    
    // Split long text into lines
    const lines = doc.splitTextToSize(text, maxLineWidth);
    doc.text(lines, margin, yPos);
    
    // Move cursor down based on number of lines
    yPos += (lines.length * (fontSize * 0.5)) + 5;
    
    // Check for new page
    if (yPos >= 280) {
      doc.addPage();
      yPos = 20;
    }
  };

  // --- 1. HEADER ---
  doc.setFillColor(15, 23, 42); // Slate-900
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Deal-Breaker Report", margin, 25);
  
  yPos = 50;

  // --- 2. FILE INFO & SCORE ---
  addText(`File: ${filename}`, 12, 'normal', [100, 116, 139]);
  
  // Score Logic
  let scoreColor = [22, 163, 74]; // Green
  if (analysis.safety_score < 50) scoreColor = [220, 38, 38]; // Red
  else if (analysis.safety_score < 80) scoreColor = [202, 138, 4]; // Yellow

  addText(`Safety Score: ${analysis.safety_score}/100`, 18, 'bold', scoreColor);
  yPos += 5;

  // --- 3. SUMMARY ---
  addText("Executive Summary:", 14, 'bold', [15, 23, 42]);
  addText(analysis.summary, 12, 'normal', [51, 65, 85]);
  yPos += 10;

  // --- 4. RED FLAGS ---
  addText(`Identified Risks (${analysis.red_flags.length})`, 16, 'bold', [220, 38, 38]);
  doc.setDrawColor(220, 38, 38);
  doc.line(margin, yPos - 3, pageWidth - margin, yPos - 3); // Underline
  yPos += 10;

  analysis.red_flags.forEach((flag, index) => {
    // Risk Title
    addText(`${index + 1}. ${flag.risk}`, 12, 'bold', [15, 23, 42]);
    
    // Severity Badge text
    addText(`[Severity: ${flag.severity.toUpperCase()}]`, 10, 'bold', flag.severity === 'High' ? [220, 38, 38] : [202, 138, 4]);

    // Original Clause (Grey box style)
    doc.setFont("courier", "italic");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    
    const clauseLines = doc.splitTextToSize(`"${flag.clause}"`, maxLineWidth - 10);
    doc.text(clauseLines, margin + 5, yPos);
    yPos += (clauseLines.length * 5) + 10;

    // Page Break Check
    if (yPos >= 270) {
      doc.addPage();
      yPos = 20;
    }
  });

  // --- 5. FOOTER ---
  const today = new Date().toLocaleDateString();
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by Deal-Breaker AI on ${today}`, margin, 290);

  // Save File
  doc.save("Deal_Breaker_Analysis.pdf");
};